config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :users, only: [:show] do
    get 'attendance' => 'attendances#attendance'
    get 'work' => 'attendances#work'
    get 'todo/:date' => 'attendances#show', as: 'todo'
    post 'start_work' => 'attendances#start_work'
    post 'end_work' => 'attendances#end_work'
    post 'attendance' => 'attendances#create_todo'
    patch 'attendance' => 'attendances#update_todo', as: 'update_todo'
    delete 'attendance' => 'attendances#destroy_todo', as: 'destroy_todo'
  end

  namespace :admin do
    get 'attendance' => 'attendances#attendance'
    post 'attendance' => 'attendances#new_shift'
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user

    def self.get_todo_info(date, user_id)
      todos = Todo.where(date: date, user_id: user_id)
    end

    def self.count_task_is_completed_false(todos)
      todos.select { |todo| !todo.is_completed }.count
    end
end

app/controllers/admin/attendances_controller.rb
class Admin::AttendancesController < ApplicationController
  def attendance
    @active_nav = :attendance
    @shift = Shift.new
    @users = User.where(admin: false)
    @user_id = params[:user_id]
    @user_name = User.find(params[:user_id]).name if params[:user_id]
    @year = params[:year].to_i
    @month = params[:month].to_i
    @get_attendance_info = get_attendance_info(@year, @month)
    @get_shift_info = get_shift_info(@year, @month, @user_id)
  end

  def new_shift
    user_id = params[:shift][:user_id]
    @shift = Shift.new(shift_params)
    @shift.user_id = user_id
    if @shift.save
        @shift = Shift.new
        @users = User.all
        @user_id = user_id
        @user_name = User.find(@user_id).name
        @year = params[:shift][:year].to_i
        @month = params[:shift][:month].to_i
        @get_attendance_info = get_attendance_info(@year, @month)
        @get_shift_info = get_shift_info(@year, @month, @user_id)
        flash.now[:notice] = "シフト作成に成功しました"
        render :attendance
    else
        flash[:notice] = "シフト作成に失敗しました"
        redirect_to admin_attendance_path
    end
  end

  private

  def shift_params
    params.require(:shift).permit(:user_id, :year, :month, :day, :start_time_hour, :start_time_minute, :end_time_hour, :end_time_minute)
  end

  def formatting_week(week)
    weeks = {
      :Sunday => "日",
      :Monday => "月",
      :Tuesday => "火",
      :Wednesday => "水",
      :Thursday => "木",
      :Friday => "金",
      :Saturday => "土"
    }
    return weeks[week.to_sym]
  end

  def get_attendance_info(year, month)
    if year == 0 and month == 0
        year = Date.current.year
        month = Date.current.month
    end
    start_date = Time.new(year, month, 1).beginning_of_month
    end_date = Time.new(year, month, 1).end_of_month
    get_attendance_info = (start_date.to_date..end_date.to_date).map do |date|
      attendance = Attendance.find_by(start_time: date.beginning_of_day..date.end_of_day, user_id: @user_id)
      if attendance and attendance.start_time != nil and attendance.end_time != nil
        start_time = attendance.start_time.strftime("%H:%M")
        end_time = attendance.end_time.strftime("%H:%M")
      elsif attendance and attendance.end_time == nil
        start_time = attendance.start_time.strftime("%H:%M")
        end_time = nil
      else
        start_time = nil
        end_time = nil
      end
      { date: date, day_of_week: formatting_week(date.strftime("%A")), start_time: start_time, end_time: end_time }
    end
    return get_attendance_info
  end

  def get_shift_info(year, month, user_id)
    if year == 0 and month == 0
        year = Date.current.year
        month = Date.current.month
    end
    start_date = Time.new(year, month, 1).beginning_of_month
    end_date = Time.new(year, month, 1).end_of_month
    get_shift_info = (start_date.to_date..end_date.to_date).map do |date|
      day = date.day
      # shift = Shift.where(year: year).where(month: month).where(day: day).where(user_id: current_user.id)
      shift = Shift.find_by(year: year, month: month, day: day, user_id: user_id)
      if shift.present?
        start_time_hour = shift.start_time_hour.to_s
        end_time_hour = shift.end_time_hour.to_s
        # 分の数が1桁の場合に、2桁目に0を補充するように
        start_time_minute = sprintf("%02d", shift.start_time_minute)
        end_time_minute = sprintf("%02d", shift.end_time_minute)
        start_time = "#{start_time_hour}:#{start_time_minute}"
        end_time = "#{end_time_hour}:#{end_time_minute}"
      end

      { date: date, day_of_week: formatting_week(date.strftime("%A")), start_time: start_time, end_time: end_time }
    end
    return get_shift_info
  end

end

app/controllers/attendances_controller.rb
require 'date'
class AttendancesController < ApplicationController
    def attendance
      @active_nav = :attendance
      @todo = Todo.new
      @year = params[:year].to_i
      @month = params[:month].to_i
      @get_attendance_info = get_attendance_info(@year, @month)
      @get_shift_info = get_shift_info(@year, @month)
    end

    def show
      @todos = Todo.where(user_id: params[:user_id], date: params[:date])
      @user_id = params[:user_id]
      @date = params[:date]
    end

    def update_todo
      @active_nav = :attendance
      todo = Todo.find(params[:id])
      if todo.update(todo_params)
        @year = todo.date.year
        @month = todo.date.month
        @get_attendance_info = get_attendance_info(@year, @month)
        @get_shift_info = get_shift_info(@year, @month)
        @todo = Todo.new
        flash.now[:notice] = 'タスクの更新に成功しました'
        render :attendance
      else
        @year = todo.date.year
        @month = todo.date.month
        @get_attendance_info = get_attendance_info(@year, @month)
        @get_shift_info = get_shift_info(@year, @month)
        @todo = Todo.new
        flash.now[:notice] = 'タスクの更新に失敗しました'
        render :attendance
      end
      
    end

    def destroy_todo
      @active_nav = :attendance
      todo = Todo.find(params[:id])
      @year = todo.date.year
      @month = todo.date.month
      todo.destroy
      @get_attendance_info = get_attendance_info(@year, @month)
      @get_shift_info = get_shift_info(@year, @month)
      @todo = Todo.new
      render :attendance
    end


    def work
      @active_nav = :work
      attendance = current_user.attendances.last
      if attendance
        @status = attendance.status
      else
        @status = false
      end
    end

    def start_work
      @attendance = Attendance.new(user_id: current_user.id, start_time: Time.zone.now, status: true)
      if @attendance.save
        flash[:success] = "出勤しました。"
      else
        flash[:error] = "出勤できませんでした。"
      end
      redirect_to user_work_path(current_user.id)
    end
    
    def end_work
      @attendance = current_user.attendances.last
      if @attendance.update(end_time: Time.zone.now, status: false)
        flash[:success] = "退勤しました。"
      else
        flash[:error] = "退勤できませんでした。"
      end
      redirect_to user_work_path(current_user.id)
    end

    def create_todo
      @active_nav = :attendance
      todo = Todo.new(todo_params)
      if todo.save
        @year = todo.date.year
        @month = todo.date.month
        @get_attendance_info = get_attendance_info(@year, @month)
        @get_shift_info = get_shift_info(@year, @month)
        @todo = Todo.new
        flash.now[:notice] = 'タスクの作成に成功しました'
        render :attendance
      else
        @year = todo.date.year
        @month = todo.date.month
        @get_attendance_info = get_attendance_info(@year, @month)
        @get_shift_info = get_shift_info(@year, @month)
        @todo = Todo.new
        flash.now[:notice] = 'タスクの作成に失敗しました'
        render :attendance
      end
    end

    private
    def time_params
      params.require(:attendance).permit(:start_time, :end_time, :status)
    end

    def todo_params
      params.require(:todo).permit(:user_id, :task, :is_completed, :date)
    end

    def formatting_week(week)
      weeks = {
        :Sunday => "日",
        :Monday => "月",
        :Tuesday => "火",
        :Wednesday => "水",
        :Thursday => "木",
        :Friday => "金",
        :Saturday => "土"
      }
      return weeks[week.to_sym]
    end

    def get_attendance_info(year, month)
      if year == 0 and month == 0
          year = Date.current.year
          month = Date.current.month
      end
      start_date = Time.new(year, month, 1).beginning_of_month
      end_date = Time.new(year, month, 1).end_of_month
      get_attendance_info = (start_date.to_date..end_date.to_date).map do |date|
        attendance = Attendance.find_by(start_time: date.beginning_of_day..date.end_of_day, user_id: current_user.id)
        if attendance and attendance.start_time != nil and attendance.end_time != nil
          start_time = attendance.start_time.strftime("%H:%M")
          end_time = attendance.end_time.strftime("%H:%M")
        elsif attendance and attendance.end_time == nil
          start_time = attendance.start_time.strftime("%H:%M")
          end_time = nil
        else
          start_time = nil
          end_time = nil
        end
        todos = Attendance.get_todo_info(date, current_user.id)
        { date: date, day_of_week: formatting_week(date.strftime("%A")), start_time: start_time, end_time: end_time, todos: todos }
      end
      return get_attendance_info
    end

    def get_shift_info(year, month)
      if year == 0 and month == 0
          year = Date.current.year
          month = Date.current.month
      end
      start_date = Time.new(year, month, 1).beginning_of_month
      end_date = Time.new(year, month, 1).end_of_month
      get_shift_info = (start_date.to_date..end_date.to_date).map do |date|
        day = date.day
        # shift = Shift.where(year: year).where(month: month).where(day: day).where(user_id: current_user.id)
        shift = Shift.find_by(year: year, month: month, day: day, user_id: current_user.id)
        if shift.present?
          start_time_hour = shift.start_time_hour.to_s
          end_time_hour = shift.end_time_hour.to_s
          # 分の数が1桁の場合に、2桁目に0を補充するように
          start_time_minute = sprintf("%02d", shift.start_time_minute)
          end_time_minute = sprintf("%02d", shift.end_time_minute)
          start_time = "#{start_time_hour}:#{start_time_minute}"
          end_time = "#{end_time_hour}:#{end_time_minute}"
        end

        { date: date, day_of_week: formatting_week(date.strftime("%A")), start_time: start_time, end_time: end_time }
      end
      return get_shift_info
    end
end

app/helpers/admin/attendances_helper.rb
module Admin::AttendancesHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_todo.html.erb
<%= form_with model: todo, url: user_attendance_path, local: true do |f| %>
<%= f.hidden_field :user_id, value: current_user.id %>
<%= f.text_field :task, placeholder: "タスクを入力してください" %>
<%= f.hidden_field :date, value: date %>
<%= f.submit '作成', class: 'btn btn-primary', data: { turbo: false } %>
<% end %>

app/views/attendances/attendance.html.erb

<%= flash[:notice] %>
<%= form_with url: user_attendance_path(current_user.id), local: true, method: :get do |f| %>
<%= f.select :year, (Date.current.year - 5..Date.current.year + 1), { selected: @year } %><span>年</span>
<%= f.select :month, (1..12), { selected: @month } %><span>月の情報を</span>
<%= f.submit '表示', class: "btn btn-primary" %>
<% end %>

<table class="table table-Hoverable">
<thead>
<tr>
<th>日付</th>
<th>やること</th>
<th>シフト時間</th>
<th>勤怠情報</th>
</tr>
</thead>
<tbody>
<% @get_attendance_info.zip(@get_shift_info) do |attendance, shift| %>
<tr>
<td><%= "#{attendance[:date]} (#{attendance[:day_of_week]})" %></td>
<td class="todo">

<%= turbo_frame_tag "todos-#{attendance[:date]}-#{current_user.id}" do %>
<div class="d-flex align-items-center">
  <%= link_to '詳細', user_todo_path(user_id: current_user.id, date: attendance[:date]), class: 'btn btn-info' %>
<%= render 'todo', todo: @todo, date: attendance[:date] %>
<% if Attendance.count_task_is_completed_false(attendance[:todos]) >= 1 %>
<span style="font-size: larger;">タスク残件数⇒<%= Attendance.count_task_is_completed_false(attendance[:todos]) %></span>
<% end %>
</div>
<% end %>
</td>
<td><%= "#{shift[:start_time]}～#{shift[:end_time]}" %>
<td><%= "#{attendance[:start_time]}～#{attendance[:end_time]}" %></td>
</tr>
<% end %>
</tbody>
</table>



app/views/attendances/show.html.erb
<%= turbo_frame_tag "todos-#{@date}-#{@user_id}" do %>
<%= link_to "閉じる", :back, class: 'btn btn-danger' %>
<% @todos.each do |todo| %>
<%= form_with model: todo, url: user_update_todo_path(user_id: @user_id, id: todo.id), method: :patch do |f| %>
<%= f.check_box :is_completed, { checked: todo.is_completed } %>
<%= f.text_field :task %>
<%= f.submit '更新', data: { turbo: false } %>
<%= link_to '削除', user_destroy_todo_path(user_id: @user_id, id: todo.id), 
  data: {
    turbo_method: :delete,
 }, class: 'btn btn-danger' %>
</br>
</br>
<% end %>

<% end %>
<% end %>

app/views/attendances/work.html.erb
<div class="container text-center py-5">

  <% if @status == true %>
<div style="background-color: #f0f0f0;">
<div class="display-4 fw-bold">出勤中</div>
</div>
  <div id="current-time" class="display-1 mb-4"></div>
    <%= form_with url: user_end_work_path(current_user.id), local: true, method: :post do |f| %>
      <%= f.submit '退勤', class: "btn btn-info btn-lg" %>
    <% end %>
  <% else %>
  <div style="background-color: #f0f0f0;">
<div class="display-4 fw-bold">退室中</div>
</div>
  <div id="current-time" class="display-1 mb-4"></div>
    <%= form_with url: user_start_work_path(current_user.id), local: true, method: :post do |f| %>
      <%= f.submit '出勤', class: "btn btn-success btn-lg" %>
    <% end %>
  <% end %>
</div>

<script>
  function displayCurrentTime() {
    var currentTimeElement = document.getElementById('current-time');
    var now = new Date();
    var hours = now.getHours();
    var minutes = now.getMinutes();
    var seconds = now.getSeconds();

    hours = String(hours).padStart(2, '0');
    minutes = String(minutes).padStart(2, '0');
    seconds = String(seconds).padStart(2, '0');

    currentTimeElement.textContent = hours + ':' + minutes + ':' + seconds;
  }

  displayCurrentTime();

  setInterval(displayCurrentTime, 1000);
</script>