config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :users, only: [:show] do
    get 'attendance' => 'attendances#attendance'
    get 'work' => 'attendances#work'
    get 'todo/:date' => 'attendances#show', as: 'todo'
    post 'start_work' => 'attendances#start_work'
    post 'end_work' => 'attendances#end_work'
    post 'attendance' => 'attendances#create_todo'
    patch 'attendance' => 'attendances#update_todo', as: 'update_todo'
    delete 'attendance' => 'attendances#destroy_todo', as: 'destroy_todo'
  end

  namespace :admin do
    get 'attendance' => 'attendances#attendance'
    post 'attendance' => 'attendances#new_shift'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManageApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= turbo_include_tags %>
    <script src="https://kit.fontawesome.com/a61de98c96.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "signup", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "top", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
  <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <div class="navbar-brand">
        <span>勤怠管理</span>
</div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <% if current_user.admin? %>
      <li>
        <%= link_to admin_attendance_path, class: 'nav-link text-white' do %>
        <i class="fa-solid fa-gears"></i>
        <% if @active_nav == :attendance %>
        <span class="text-yellow">管理</span>
      <% else %>
        <span>管理</span>
      <% end %>
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white' do %>
        <i class="fas fa-sign-out-alt"></i> ログアウト
        <% end %>
      </li>
      <% else %>
      <li>
        <%= link_to user_path(current_user.id), class: 'nav-link text-white' do %>
        <i class="fas fa-home"></i>
        <% if @active_nav == :user_show %>
        <span class="text-yellow">マイページ</span>
      <% else %>
        <span>マイページ</span>
      <% end %>
        <% end %>
      </li>
      <li>
        <%= link_to user_attendance_path(current_user.id), class: 'nav-link text-white' do %>
        <i class="fa-solid fa-calendar-days"></i>
        <% if @active_nav == :attendance %>
        <span class="text-yellow">勤怠情報</span>
      <% else %>
        <span>勤怠情報</span>
      <% end %>
        <% end %>
      </li>
      <li>
        <%= link_to user_work_path(current_user.id), class: 'nav-link text-white' do %>
        <i class="fa-solid fa-id-badge"></i>
        <% if @active_nav == :work %>
        <span class="text-yellow">勤怠</span>
      <% else %>
        <span>勤怠</span>
      <% end %>
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white' do %>
        <i class="fas fa-sign-out-alt"></i> ログアウト
        <% end %>
      </li>
      <% end %>
    <% else %>
    <li>
        <%= link_to root_path, class: 'nav-link text-white' do %>
        <i class="fa-solid fa-circle-info"></i><% if @active_nav == :top %>
        <span class="text-yellow">トップページ</span>
      <% else %>
        <span>トップページ</span>
      <% end %>
        <% end %>
      </li>
      <li>
        <%= link_to new_user_registration_path, class: 'nav-link text-white' do %>
        <i class="fas fa-user-plus"></i> 新規登録
        <% end %>
      </li>
      <li>
        <%= link_to new_user_session_path, class: 'nav-link text-white' do %>
        <i class="fas fa-sign-in-alt"></i> ログイン
        <% end %>
      </li>
      <% end %>
      </ul>
      </div>
      </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>